# Generated by Django 4.2.6 on 2023-10-18 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_property_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="categoty",
            new_name="category",
        ),
    ]
