# Generated by Django 4.2.6 on 2023-10-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_categoty_property_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="imgage",
            field=models.ImageField(
                default="property-01.jpg", upload_to="site_images/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[
                    ("APARTMENT", "APARTMENT"),
                    ("VILLA HOUSE", "VILLA HOUSE"),
                    ("PENTHOUSE", "PENTHOUSE"),
                    ("MORDERN CONDO", "MORDERN CONDO"),
                ],
                max_length=50,
            ),
        ),
    ]
