# Generated by Django 4.2.6 on 2023-10-18 10:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_property_imgage_alter_category_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="imgage",
            new_name="image",
        ),
    ]
