# Generated by Django 4.2.6 on 2024-01-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_contactus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="image",
            field=models.FileField(upload_to="images/"),
        ),
    ]
